name: route_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=3.0.0 <=4.0.0'

# Add regular dependencies here.
dependencies:
  route_annotations:
    ## make sure this is correct path
    # generally it's a published package
    path: ../route_annotations
  build: ^2.4.1
  source_gen: ^1.5.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
